"""engine/deps.py — 内核依赖注入契约（DB / Store / Stage 服务）。

设计目标：内核不负责“如何构造 db / store / stage 服务”，只负责“使用满足契约的实例”。

调用方可传入：
  - deps.db：一个现成的 DB 实例（优先）
  - deps.store：一个现成的 Store 实例（优先）
  - deps.db_factory：无参工厂，需要时由内核调用
  - deps.store_factory：无参工厂，需要时由内核调用
  - deps.stages：自定义 stage 注册表 {step_name: Stage}
  - deps.doc_id_factory：自定义文档 ID 生成函数
  - deps.exception_classifier：自定义异常分类函数

未传任何依赖时，内核回退到默认实现（general_stages 默认工厂），
保持既有行为不变。
"""
from dataclasses import dataclass
from typing import Any, Callable, Optional, Protocol


class DB(Protocol):
    """SQLite / 任意持久化层需满足的内核 DB 契约。"""

    def get_steps(self, doc_unique_id: str) -> list[dict]: ...
    def set_step(self, doc_unique_id: str, step: str, status: str,
                 payload_ref: str = "", last_error: str = "", attempts: int = 0) -> None: ...
    def outbox_record(self, doc_unique_id: str, op: str, status: str,
                      chunk_ids: list | None = None, expected_chunks: int = 0,
                      last_error: str = "") -> None: ...
    def outbox_status_of(self, doc_unique_id: str, op: str = "write") -> str | None: ...
    def outbox_pending_rows(self, status: str = "pending") -> list[dict]: ...
    def write_chunks(self, rows: list[dict]) -> list[int]: ...
    def delete_doc_chunks(self, doc_unique_id: str) -> int: ...
    def count_doc_chunks(self, doc_unique_id: str) -> int: ...
    def fetch_doc_chunks(self, doc_unique_id: str) -> list[dict]: ...
    def list_doc_ids(self) -> list[str]: ...
    def add_failed(self, *args: Any, **kwargs: Any) -> None: ...
    def add_fatal(self, *args: Any, **kwargs: Any) -> None: ...
    def add_empty_chunk(self, *args: Any, **kwargs: Any) -> Any: ...


class Store(Protocol):
    """向量库 / 任意检索存储需满足的内核 Store 契约。"""

    def create_if_missing(self, schema: Any) -> bool: ...
    def write_overwrite(self, rows: list[dict[str, Any]]) -> list[int]: ...
    def delete_doc(self, doc_unique_id: str) -> None: ...
    def delete_chunk_ids(self, chunk_ids: list[int]) -> int: ...
    def fetch_doc_rows(self, doc_unique_id: str) -> list[dict[str, Any]]: ...
    def list_doc_ids(self) -> list[str]: ...
    def count_rows(self) -> int: ...
    def check_chunks_exist(self, chunk_ids: list[int]) -> dict[int, bool]: ...
    def full_scan(self) -> Any: ...


@dataclass
class Deps:
    """内核依赖注入容器。所有字段均可选。"""

    db: Optional[DB] = None
    store: Optional[Store] = None
    db_factory: Optional[Callable[[], DB]] = None
    store_factory: Optional[Callable[[], Store]] = None

    # Stage 注册表：{step_name: Stage}，默认使用 general_stages.GENERAL_STAGE_REGISTRY
    stages: Optional[dict[str, Any]] = None

    # 文档 ID 生成：callable(tenant_id, file_md5) -> str
    doc_id_factory: Optional[Callable[[str, str], str]] = None

    # 异常分类：callable(exception) -> dict（retry_exception.yaml 分类结果）
    exception_classifier: Optional[Callable[[Exception], dict]] = None
